import { ArrowUpRight, Instagram, Mail } from "lucide-react";

function SiteHeader() {
  return <header className="site-header"><div className="header-inner"><a className="brand" href="/" aria-label="Retro Event home"><span className="brand-wordmark">RETRO <em>EVENT</em></span></a><nav className="main-nav" aria-label="Primary navigation"><a href="/#the-vibe">The vibe</a><a href="/#how-it-works">How it works</a><a href="/#ramp-walk">The ramp walk</a><a href="/#faq">FAQ</a><a className="button button-coral nav-register" href="/register">Register <ArrowUpRight size={15} /></a></nav></div></header>;
}

export default function About() {
  return <div className="site-shell about-page"><SiteHeader /><main><section className="about-section section-pad"><div className="page-width about-layout"><div className="about-copy"><div className="section-kicker">ABOUT THE ORGANIZER</div><h1>Good nights<br /><span>start with<br />good people.</span></h1><p className="about-lede">Retro Event is being organized by <strong>Sabir Hussain, a teacher</strong>, who wanted to create a night where people can dress up, show up, and celebrate the style that made the 70s and 80s unforgettable.</p><div className="about-placeholder"><b>[FILL IN: 2-3 sentences on why you're organizing this]</b><p>[FILL IN: Add any additional organizer context you want attendees to know]</p></div><div className="about-links"><a href="mailto:hello@retroevent.example"><Mail size={16} /> hello@retroevent.example</a><a href="#social"><Instagram size={16} /> [FILL IN: social link]</a></div></div><div className="about-portrait"><div className="about-photo-placeholder"><span>[FILL IN: organizer photo]</span></div><div className="about-caption"><span>THE PERSON<br />BEHIND THE NIGHT</span><span className="caption-arrow">↗</span></div></div></div></section></main><footer className="site-footer"><div className="page-width footer-grid"><a className="brand" href="/"><span className="brand-wordmark">RETRO <em>EVENT</em></span></a><div className="footer-signoff"><span>MAKE AN<br />ENTRANCE.</span></div></div><div className="page-width footer-bottom"><span>© 2026 RETRO EVENT</span><span>[FILL IN: organizer social handle]</span></div></footer></div>;
}
