import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowUpRight, CalendarPlus, Check, CircleAlert, CreditCard, Download, Instagram, Mail, QrCode, Share2, Smartphone, Sparkles, Users, WalletCards } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";

const ticketOptions = [
  { id: "general", title: "General entry", subtitle: "Watch, cheer, dance", price: 0, spots: 180 },
  { id: "solo", title: "Contestant · Ramp Walk", subtitle: "One look. One unforgettable entrance.", price: 999, spots: 42 },
  { id: "group", title: "Group entry", subtitle: "For crews and coordinated energy", price: 1999, spots: 12 },
] as const;
const categoryLabels: Record<string, string> = { general: "General entry", solo: "Contestant · Ramp Walk", group: "Group entry" };
const emptyMember = { name: "", contact: "" };

function SiteHeader() { return <header className="site-header"><div className="header-inner"><a className="brand" href="/" aria-label="Retro Event home"><span className="brand-wordmark">RETRO <em>EVENT</em></span></a><a className="back-link" href="/"><ArrowLeft size={15} /> Back to event</a></div></header>; }
function FieldError({ children }: { children: string }) { return <small className="field-error"><CircleAlert size={13} /> {children}</small>; }

export default function Register() {
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [registrationCode, setRegistrationCode] = useState("");
  const [terms, setTerms] = useState(false);
  const [members, setMembers] = useState([{ ...emptyMember }]);
  const [form, setForm] = useState({ ticketType: "solo", fullName: "", email: "", phone: "", instagram: "", decade: "mix", look: "" });
  const ticket = useMemo(() => ticketOptions.find((option) => option.id === form.ticketType) || ticketOptions[1], [form.ticketType]);
  const setField = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const updateMember = (index: number, key: "name" | "contact", value: string) => setMembers((current) => current.map((member, i) => i === index ? { ...member, [key]: value } : member));
  const stepValid = step === 1 ? Boolean(form.ticketType) : step === 2 ? Boolean(form.fullName && form.email && form.phone) : step === 3 ? Boolean(form.decade) : terms;

  function next(event?: FormEvent) {
    event?.preventDefault(); setError("");
    if (!stepValid) return;
    if (step < 4) setStep((current) => current + 1); else void submitRegistration();
  }
  async function submitRegistration() {
    try {
      const response = await fetch("/api/registrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: form.fullName, phone: form.phone, email: form.email, instagram: form.instagram, dateOfBirth: "not-collected", decade: form.decade, category: form.ticketType, companionDetails: form.ticketType === "group" ? members.map((member) => `${member.name} — ${member.contact}`).join("; ") : "", rampLook: form.look }) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "We couldn’t save your registration.");
      setRegistrationCode(payload.registrationCode); setSubmitted(true);
    } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "We couldn’t save your registration."); }
  }
  function addCalendar() { const ics = ["BEGIN:VCALENDAR", "VERSION:2.0", "BEGIN:VEVENT", "DTSTART:20260930T180000", "DTEND:20260930T220000", "SUMMARY:Retro Event — Costume Contest", "LOCATION:Ranchi", "END:VEVENT", "END:VCALENDAR"].join("\\r\\n"); const url = URL.createObjectURL(new Blob([ics], { type: "text/calendar" })); const link = document.createElement("a"); link.href = url; link.download = "retro-event.ics"; link.click(); URL.revokeObjectURL(url); }
  async function shareCard() { if (navigator.share) await navigator.share({ title: "I’m walking the ramp", text: `I’m registered for Retro Event in Ranchi. Code: ${registrationCode}` }); else window.alert("Your share card is ready to share. Registration code: " + registrationCode); }

  return <div className="site-shell register-page"><SiteHeader /><main><section className="register-section section-pad"><div className="page-width register-wrap">{!submitted ? <><div className="section-kicker">REGISTRATION · RANCHI · 30 SEPTEMBER</div><div className="register-heading"><h1>Save your<br /><em>entrance.</em></h1><p>Five quick steps from “I have a look” to “see you under the lights.”</p></div><div className="wizard-top"><div className="wizard-label">Step {step} of 4 <span>{["Ticket type", "Your details", "Costume", "Review & pay"][step - 1]}</span></div><div className="wizard-bar"><i style={{ width: `${step * 25}%` }} /></div></div><form id="register-form" className="wizard-card" onSubmit={next}><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }} transition={{ duration: .2 }}>
    {step === 1 && <div><div className="stub-kicker">STEP 01 / TICKET TYPE</div><h2>Choose your entrance.</h2><div className="ticket-options">{ticketOptions.map((option) => <button type="button" key={option.id} className={`ticket-option ${form.ticketType === option.id ? "selected" : ""}`} onClick={() => setField("ticketType", option.id)}><span className="ticket-option-check">{form.ticketType === option.id ? <Check size={15} /> : ""}</span><span><b>{option.title}</b><small>{option.subtitle}</small></span><strong>{option.price ? `₹${option.price.toLocaleString("en-IN")}` : "FREE"}</strong><em>{option.spots} spots left</em></button>)}</div></div>}
    {step === 2 && <div><div className="stub-kicker">STEP 02 / ATTENDEE DETAILS</div><h2>Who’s walking in?</h2><div className="register-form-grid"><label>Full name *<input autoFocus required value={form.fullName} onChange={(e) => setField("fullName", e.target.value)} placeholder="Your name" />{!form.fullName && <FieldError>We need a name for the guest list.</FieldError>}</label><label>Email address *<input required type="email" value={form.email} onChange={(e) => setField("email", e.target.value)} placeholder="you@email.com" /></label><label>Phone number *<input required type="tel" value={form.phone} onChange={(e) => setField("phone", e.target.value)} placeholder="+91 00000 00000" /><small className="integration-note"><Smartphone size={13} /> OTP verification connects in Phase 2.</small></label><label>Instagram <span className="optional">optional</span><input value={form.instagram} onChange={(e) => setField("instagram", e.target.value)} placeholder="@yourhandle" /></label></div>{form.ticketType === "group" && <div className="members-box"><div className="members-heading"><b><Users size={16} /> Group members</b><button type="button" onClick={() => setMembers((current) => [...current, { ...emptyMember }])}>+ Add another person</button></div>{members.map((member, index) => <div className="member-row" key={index}><input aria-label={`Member ${index + 1} name`} value={member.name} onChange={(e) => updateMember(index, "name", e.target.value)} placeholder={`Person ${index + 1} name`} /><input aria-label={`Member ${index + 1} contact`} value={member.contact} onChange={(e) => updateMember(index, "contact", e.target.value)} placeholder="Phone or email" /></div>)}</div>}</div>}
    {step === 3 && <div><div className="stub-kicker">STEP 03 / COSTUME CATEGORY</div><h2>Find your era.</h2><p className="step-copy">Choose the flavour your look is bringing to the room. This helps our judges set the mood.</p><div className="chip-selector">{[["70s", "70s"], ["80s", "80s"], ["mix", "Mixed-decade"]].map(([id, label]) => <button type="button" className={form.decade === id ? "active" : ""} key={id} onClick={() => setField("decade", id)}>{label}</button>)}</div><label className="look-field">Describe your look <span className="optional">optional</span><textarea value={form.look} onChange={(e) => setField("look", e.target.value)} placeholder="Disco diva, arcade hero, power shoulders…" /></label></div>}
    {step === 4 && <div><div className="stub-kicker">STEP 04 / REVIEW & PAY</div><h2>One last look.</h2><div className="order-summary"><div><span>{categoryLabels[form.ticketType]} × 1</span><b>{ticket.price ? `₹${ticket.price.toLocaleString("en-IN")}` : "FREE"}</b></div><div><span>Registration fee</span><b>₹0</b></div><div className="summary-total"><span>Total</span><b>{ticket.price ? `₹${ticket.price.toLocaleString("en-IN")}` : "FREE"}</b></div></div><div className="phase2-callout"><CreditCard size={20} /><div><b>Razorpay checkout is next.</b><p>Payment is staged for Phase 2. Your registration details will be saved now, and UPI, cards, and netbanking will plug into this exact step.</p></div></div><label className="agreement"><input type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)} /> <span>I agree to the <a href="/terms" target="_blank" rel="noreferrer">Terms & Conditions</a> and <a href="/refund-policy" target="_blank" rel="noreferrer">Refund Policy</a>.</span></label></div>}
  </motion.div></AnimatePresence></form>{error && <div className="form-error"><CircleAlert size={16} /> {error}</div>}<div className="wizard-actions"><button className="button button-dark" type="button" onClick={() => step > 1 ? setStep((current) => current - 1) : window.location.assign("/")}>{step > 1 ? "Back" : "Cancel"}</button><button className="button button-coral" type="submit" form="register-form" disabled={!stepValid}>{step === 4 ? "Pay & register" : "Continue"} <ArrowUpRight size={17} /></button></div><div className="phase-flow compact-flow"><div><Smartphone size={15} /><b>OTP</b></div><i /><div><CreditCard size={15} /><b>Payment</b></div><i /><div><WalletCards size={15} /><b>Digital ticket</b></div></div></> : <div className="wizard-success"><div className="success-sparkles"><Sparkles size={24} /><span>✦</span><span>✳</span></div><div className="stub-kicker">REGISTRATION SAVED</div><h1>You’re on the<br /><em>list.</em></h1><p>Your details are safely stored. We’ll send an email and SMS when the ticket links go live.</p><div className="walking-card"><div><b>I’M WALKING<br />THE RAMP</b><span>RETRO EVENT · RANCHI · 30 SEPTEMBER</span><small>{categoryLabels[form.ticketType]} · {registrationCode}</small></div><QrCode size={46} /></div><div className="success-actions"><button className="button button-dark" onClick={addCalendar}><CalendarPlus size={16} /> Add to calendar</button><button className="button button-coral" onClick={shareCard}><Share2 size={16} /> Share card</button><button className="button button-light" onClick={() => window.print()}><Download size={16} /> Download card</button></div><a className="mail-link" href="mailto:[CONTACT EMAIL]"><Mail size={16} /> [CONTACT EMAIL]</a></div>}</div></section></main></div>;
}
